<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE event [<!ELEMENT zip_code (#PCDATA)><!ELEMENT url_link_display (#PCDATA)><!ELEMENT url (#PCDATA)><!ELEMENT tracks (track+)><!ELEMENT track (#PCDATA)><!ELEMENT title (#PCDATA)><!ELEMENT timeslot (slot_id?, title, room, date, start_time, end_time, description?, acm_doi?, persons?, tracks?, tags?)><!ELEMENT tags (tag+)><!ELEMENT tag (#PCDATA)><!ELEMENT suffix (#PCDATA)><!ELEMENT subevent_logo_url (#PCDATA)><!ELEMENT subevent_id (#PCDATA)><!ELEMENT subevent (subevent_id?, title, acronym?, subevent_type, description?, room, date, url?, url_link_display?, subevent_logo_url?, acm_doi?, persons?, tracks?, tags?, sponsor?, timeslot*)><!ELEMENT state (#PCDATA)><!ELEMENT start_time (#PCDATA)><!ELEMENT start_date (#PCDATA)><!ELEMENT sponsor (#PCDATA)><!ELEMENT sort_key (#PCDATA)><!ELEMENT slot_id (#PCDATA)><!ELEMENT subevent_type EMPTY><!ATTLIST subevent_type	type (case_study | demonstration | poster | regular | tutorial | workshop) #IMPLIED><!ELEMENT room (#PCDATA)><!ELEMENT role (#PCDATA)><!ELEMENT picture_url (#PCDATA)><!ELEMENT persons (person+)><!ELEMENT person (role, sort_key, first_name, middle_name?, last_name, suffix?, affiliation, acm_profile_id?, email?, bio?, homepage_url?, picture_url?)><!ELEMENT middle_name (#PCDATA)><!ELEMENT location (facility_name, facility_map_url?, address, city, state?, country, zip_code?)><!ELEMENT last_name (#PCDATA)><!ELEMENT homepage_url (#PCDATA)><!ELEMENT first_name (#PCDATA)><!ELEMENT facility_name (#PCDATA)><!ELEMENT facility_map_url (#PCDATA)><!ELEMENT event_type EMPTY><!ATTLIST event_type	type (conference|workshop|symposium) #IMPLIED><!ELEMENT event (event_details, subevent*, timeslot*)><!ELEMENT event_logo_url (#PCDATA)><!ELEMENT event_details (title, acronym, event_type, start_date, end_date, location, description, url?, url_link_display?, event_logo_url?, persons?)><!ELEMENT end_time (#PCDATA)><!ELEMENT end_date (#PCDATA)><!ELEMENT email (#PCDATA)><!ELEMENT description (#PCDATA)><!ELEMENT date (#PCDATA)><!ELEMENT country (#PCDATA)><!ELEMENT city (#PCDATA)><!ELEMENT bio (#PCDATA)><!ELEMENT affiliation (#PCDATA)><!ELEMENT address (#PCDATA)><!ELEMENT acronym (#PCDATA)><!ELEMENT acm_profile_id (#PCDATA)><!ELEMENT acm_doi (#PCDATA)>]>
<event>
  <event_details>
    <title>POPL 2018</title>
    <acronym>POPL 2018</acronym>
    <event_type type="conference"/>
    <start_date>2018/01/07</start_date>
    <end_date>2018/01/13</end_date>
    <location>
      <facility_name>Omni Hotel</facility_name>
      <address>251 S Olive St</address>
      <city>Los Angeles</city>
      <state>California</state>
      <country>United States</country>
    </location>
    <description>Welcome to the website of The 45th ACM SIGPLAN Symposium on Principles of Programming Languages (POPL 2018)
The annual Symposium on Principles of Programming Languages is a forum for the discussion of all aspects of programming languages and programming systems. Both theoretical and experimental papers are welcome, on topics ranging from formal frameworks to experience reports. We seek submissions that make principled, enduring contributions to the theory, design, understanding, implementation or application of programming languages.
The symposium is sponsored by ACM SIGPLAN, in cooperation with ACM SIGACT and ACM SIGLOG.
The main POPL 2018 conference will be held from Wed 10 - Fri 12 January 2018.
Please visit the track pages of co-located conferences and workshops to find their schedules.
The schedule for POPL can be found here

Schedule At A Glance

</description>
    <url>https://popl18.sigplan.org/home</url>
    <url_link_display>POPL 2018</url_link_display>
    <persons>
      <person>
        <role>Chair in Steering Committee</role>
        <sort_key>1</sort_key>
        <first_name>Giuseppe</first_name>
        <last_name>Castagna</last_name>
        <affiliation>CNRS, France / University of Paris Diderot, France</affiliation>
        <bio>undefined</bio>
        <homepage_url>http://www.irif.fr/~gc/</homepage_url>
        <picture_url>https://popl18.sigplan.org/getProfileImage/giuseppecastagna/ca2a9ac8-d149-4486-87ed-b55ceb154a17/small.jpg</picture_url>
      </person>
      <person>
        <role>General Chair in Organizing Committee, Committee Member in Steering Committee</role>
        <sort_key>2</sort_key>
        <first_name>Ranjit</first_name>
        <last_name>Jhala</last_name>
        <affiliation>University of California, San Diego</affiliation>
        <bio>Nom nom. Chomp. Burp.</bio>
        <homepage_url>http://ranjitjhala.github.io</homepage_url>
        <picture_url>https://popl18.sigplan.org/getProfileImage/ranjitjhala/afbdab69-ed23-4022-b7a4-2c57128f20ec/small.jpg</picture_url>
      </person>
      <person>
        <role>Program Chair in Organizing Committee, Committee Member in Steering Committee</role>
        <sort_key>3</sort_key>
        <first_name>Andrew</first_name>
        <last_name>Myers</last_name>
        <affiliation>Cornell University</affiliation>
        <bio>Andrew Myers is a Professor in the Department of Computer Science at Cornell University in Ithaca, NY. His research interests include programming languages, computer security, and distributed and persistent programming systems. Myers is an ACM Fellow. He has received awards for papers appearing in POPL’99, SOSP’01, SOSP’07, CIDR’13, PLDI’13, and PLDI’15. Myers is currently the Editor-in-Chief for ACM Transactions on Programming Languages and Systems (TOPLAS). He has also served as program chair or co-chair for a few conferences: ACM POPL 2018, ACM CCS 2016, POST 2014, IEEE CSF 2010, and IEEE S&amp;amp;P 2009.</bio>
        <homepage_url>http://www.cs.cornell.edu/andru</homepage_url>
        <picture_url>https://popl18.sigplan.org/getProfileImage/andrewmyers/88baadd2-5ed8-4687-b205-3cbbe8b1a848/small.jpg</picture_url>
      </person>
      <person>
        <role>Committee Member in Steering Committee</role>
        <sort_key>4</sort_key>
        <first_name>Rastislav</first_name>
        <last_name>Bodik</last_name>
        <affiliation>University of Washington</affiliation>
        <bio>undefined</bio>
        <homepage_url>http://www.cs.berkeley.edu/~bodik</homepage_url>
        <picture_url>https://popl18.sigplan.org/getProfileImage/rastislavbodik/ae16ae8e-9d00-41c4-9067-0c37da65dde7/small.jpg</picture_url>
      </person>
      <person>
        <role>Committee Member in Steering Committee</role>
        <sort_key>5</sort_key>
        <first_name>Jeremy</first_name>
        <last_name>Gibbons</last_name>
        <affiliation>Department of Computer Science, University of Oxford</affiliation>
        <bio>I am Professor of Computing in the Department of Computer Science at the University of Oxford. I am currently Director of the Software Engineering Programme, which offers part-time professional Masters’ degrees in Software Engineering and in Software and Systems Security. I also lead the Algebra of Programming research group. I am Editor-in-Chief of the Journal of Functional Programming, Past Vice Chair of ACM SIGPLAN, Past Chair of IFIP WG2.1. Before taking up this post in 1999, I held lectureships at Oxford Brookes University and the University of Auckland, New Zealand.</bio>
        <homepage_url>http://www.cs.ox.ac.uk/jeremy.gibbons/</homepage_url>
        <picture_url>https://popl18.sigplan.org/getProfileImage/jeremygibbons/17403e55-a926-41cf-ae21-08abecea187c/small.jpg</picture_url>
      </person>
      <person>
        <role>Committee Member in Steering Committee</role>
        <sort_key>6</sort_key>
        <first_name>Andrew D.</first_name>
        <last_name>Gordon</last_name>
        <affiliation>Microsoft Research and University of Edinburgh</affiliation>
        <bio>I am a Principal Researcher at Microsoft Research, Cambridge, where I manage Programming Principles and Tools. As a part-time position, I also hold the Chair in Computer Security and am a member of the Laboratory for Foundations of Computer Science and the Security and Privacy group in the School of Informatics in the University of Edinburgh. I convene the University of Edinburgh Microsoft Research Joint Initiative in Informatics. I participate in the Data Science PhD programme. My current research is on probabilistic programming for machine learning.</bio>
        <homepage_url>https://www.microsoft.com/en-us/research/people/adg/</homepage_url>
        <picture_url>https://popl18.sigplan.org/getProfileImage/andrewdgordon/6a7c06a4-cf70-4529-ad02-55b979e93f82/small.jpg</picture_url>
      </person>
      <person>
        <role>Committee Member in Steering Committee</role>
        <sort_key>7</sort_key>
        <first_name>Michael</first_name>
        <last_name>Hicks</last_name>
        <affiliation>University of Maryland, College Park</affiliation>
        <bio>Michael Hicks is a Professor in the Computer Science department and UMIACS at the University of Maryland, where he co-directs the laboratory for Programming Languages research (PLUM); he is the former Director of the Maryland Cybersecurity Center (MC2).
His research focuses on using programming languages and analyses to improve the security, reliability, and availability of software. He is perhaps best known for his work exploring dynamic software updating, which is a technique by which software can be updated without shutting it down. He has explored the design of new programming languages and analysis tools for helping programmers find bugs and software vulnerabilities, and for identifying suspicious or incorrect program executions.
His recent work has combined ideas from PL and cryptography, e.g., to ensure privacy preserving computations. He also leads the development of a new security-oriented programming contest, “build-it, break-it, fix-it,” which has been offered to the public and to students in his Coursera class on software security. He is the co-editor of the Programming Languages Enthusiast blog and Tweets at @michael_w_hicks.</bio>
        <homepage_url>http://www.cs.umd.edu/~mwh/</homepage_url>
        <picture_url>https://popl18.sigplan.org/getProfileImage/michaelhicks/aa64e3c6-3516-4e13-affe-77bc32c40565/small.jpg</picture_url>
      </person>
      <person>
        <role>Committee Member in Steering Committee</role>
        <sort_key>8</sort_key>
        <first_name>Rupak</first_name>
        <last_name>Majumdar</last_name>
        <affiliation>MPI-SWS</affiliation>
        <bio>undefined</bio>
        <homepage_url>http://www.mpi-sws.org/~rupak</homepage_url>
        <picture_url>https://popl18.sigplan.org/getProfileImage/rupakmajumdar/3289b197-9f9a-4880-94c5-d9cf6d764bb1/small.jpg</picture_url>
      </person>
      <person>
        <role>Committee Member in Steering Committee</role>
        <sort_key>9</sort_key>
        <first_name>Brigitte</first_name>
        <last_name>Pientka</last_name>
        <affiliation>McGill University</affiliation>
        <bio>undefined</bio>
        <homepage_url>http://www.cs.mcgill.ca/~bpientka/</homepage_url>
        <picture_url>https://popl18.sigplan.org/getProfileImage/brigittepientka/de1fcba2-a8fd-4b6e-a4f2-b7d397fef2cf/small.jpg</picture_url>
      </person>
      <person>
        <role>Committee Member in Steering Committee</role>
        <sort_key>10</sort_key>
        <first_name>Peter</first_name>
        <last_name>Thiemann</last_name>
        <affiliation>University of Freiburg, Germany</affiliation>
        <bio>undefined</bio>
        <picture_url>https://popl18.sigplan.org/getProfileImage/peterthiemann/43fc0175-1745-4b3a-b626-86e10da76b86/small.jpg</picture_url>
      </person>
      <person>
        <role>Committee Member in Steering Committee</role>
        <sort_key>11</sort_key>
        <first_name>Jan</first_name>
        <last_name>Vitek</last_name>
        <affiliation>Northeastern University</affiliation>
        <bio>Jan Vitek is a Professor of Computer Science at Northeastern University. Dr. Vitek was born in Czechoslovakia and educated in Switzerland. Over the years, he worked on topics related to programming languages, their design, use, and implementation. With Noble and Potter, he proposed the notion of flexible alias control which became know as Ownership Types. He led the Ovm project which produced the first real-time Java virtual machine to be flight tested on a ScanEagle drone (he claims no one was harmed). Outcomes of this project include the Schism real-time garbage collector and the FijiVM – a production VM for embedded systems. More recently, he worked on dynamic languages, trying to make sense of JavaScript and to design a new language called, Thorn. Nowadays, he spends his time with statisticians and data scientists. Jan believes that his 2012 election as Chair of SIGPLAN was an accident; since has been busy trying to rock the boat to ensure this does not happen again. In his spare time, Jan enjoys organizing conferences and sitting on PCs (over 25 in the last decade). He founded the MOS (mobile objects), IWACO (alias control), STOP (gradual typing), and TRANSACT (transactional memory) workshop series. He was the first program chair of VEE and chaired ESOP, ECOOP, Coordination and TOOLS. He was the general chair of PLDI (in Beijing!), ISMM and LCTES. He may still be sitting on the steering committees of ECOOP, JTRES, ICFP, OOPLSA, POPL, PLDI, LCTES, ESOP.</bio>
        <homepage_url>http://janvitek.org</homepage_url>
        <picture_url>https://popl18.sigplan.org/getProfileImage/janvitek/213b9734-8942-47ea-933d-6ffad4bb1ee6/small.jpg</picture_url>
      </person>
      <person>
        <role>Industrial Relations Chair in Organizing Committee, Committee Member in Steering Committee</role>
        <sort_key>12</sort_key>
        <first_name>David</first_name>
        <last_name>Walker</last_name>
        <affiliation>Princeton University</affiliation>
        <bio>undefined</bio>
        <homepage_url>http://www.cs.princeton.edu/~dpw/</homepage_url>
        <picture_url>https://popl18.sigplan.org/getProfileImage/davidwalker/8763137a-03a5-4963-8639-e9f2a3cc8ac9/small.jpg</picture_url>
      </person>
      <person>
        <role>Associated Events Chair in Organizing Committee</role>
        <sort_key>13</sort_key>
        <first_name>Marco</first_name>
        <last_name>Gaboardi</last_name>
        <affiliation>University at Buffalo, SUNY</affiliation>
        <bio>Marco Gaboardi is an assistant professor in the Department of Computer Science and Engineering at the University at Buffalo, SUNY. Previously, he was a faculty at the University of Dundee, Scotland. He received his PhD from the University of Torino, Italy, and the Institute National Polytechnique de Lorraine, France. He was a visitor scholar at the University of Pennsylvania and at Harvard’s CRCS center. He has been the recipient of a EU Marie Curie Fellowship. His research is in programming languages, differential privacy, and logic.</bio>
        <homepage_url>http://www.buffalo.edu/~gaboardi</homepage_url>
        <picture_url>https://popl18.sigplan.org/getProfileImage/marcogaboardi/76ff8963-9672-4f16-87bc-3f0d75ce589b/small.jpg</picture_url>
      </person>
      <person>
        <role>Remote Participation Chair in Organizing Committee</role>
        <sort_key>14</sort_key>
        <first_name>Michael</first_name>
        <last_name>Greenberg</last_name>
        <affiliation>Pomona College</affiliation>
        <bio>undefined</bio>
        <homepage_url>http://www.cs.pomona.edu/~michael/</homepage_url>
        <picture_url>https://popl18.sigplan.org/getProfileImage/michaelgreenberg/3c177ea6-ac3c-4ddb-9f4e-ac5d7b568e07/small.jpg</picture_url>
      </person>
      <person>
        <role>Artefact Evaluation Co-Chair in Organizing Committee, Publicity Chair in Organizing Committee</role>
        <sort_key>15</sort_key>
        <first_name>Jean</first_name>
        <last_name>Yang</last_name>
        <affiliation>Carnegie Mellon University</affiliation>
        <bio>undefined</bio>
        <homepage_url>jeanyang@csail.mit.edu </homepage_url>
        <picture_url>https://popl18.sigplan.org/getProfileImage/jeanyang/728ddfd8-02f1-426b-9006-87ba458c369f/small.jpg</picture_url>
      </person>
      <person>
        <role>Student Research Competition Chair in Organizing Committee</role>
        <sort_key>16</sort_key>
        <first_name>Benjamin</first_name>
        <last_name>Delaware</last_name>
        <affiliation>Purdue University</affiliation>
        <bio>undefined</bio>
        <homepage_url>https://www.cs.purdue.edu/homes/bendy/</homepage_url>
        <picture_url>https://popl18.sigplan.org/getProfileImage/benjamindelaware/39bbf6b3-d145-435c-8956-8acf8cfcaffa/small.jpg</picture_url>
      </person>
      <person>
        <role>Artifact Evaluation Co-Chair in Organizing Committee</role>
        <sort_key>17</sort_key>
        <first_name>Cătălin</first_name>
        <last_name>Hriţcu</last_name>
        <affiliation>Inria Paris</affiliation>
        <bio>Catalin is a tenured Research Scientist at Inria Paris where he develops rigorous formal techniques for solving security problems. He is particularly interested in formal methods for security (memory safety, compartmentalization, dynamic monitoring, integrity, security protocols, information flow), programming languages (type systems, verification, proof assistants, property-based testing, semantics, formal metatheory, certified tools), and the design and verification of security-critical systems (reference monitors, secure compilers, microkernels, secure hardware). He is actively involved in the design of the F* verification system and was recently awarded an ERC Starting Grant on secure compilation. Catalin was a PhD student at Saarland University and a Research Associate at University of Pennsylvania before joining Inria Paris in 2013.</bio>
        <homepage_url>http://prosecco.gforge.inria.fr/personal/hritcu/</homepage_url>
        <picture_url>https://popl18.sigplan.org/getProfileImage/catalinhritcu/e262cec6-3e6b-47cc-ad61-b5c5b07953a1/small.jpg</picture_url>
      </person>
      <person>
        <role>Website Chair in Organizing Committee</role>
        <sort_key>18</sort_key>
        <first_name>Rohit</first_name>
        <last_name>Singh</last_name>
        <affiliation>CSAIL, MIT</affiliation>
        <bio>undefined</bio>
        <homepage_url>http://rohitsingh.net</homepage_url>
        <picture_url>https://popl18.sigplan.org/getProfileImage/rohitsingh/126f8dee-6723-4b4d-8e88-b451c7dc5b62/small.jpg</picture_url>
      </person>
      <person>
        <role>Student Volunteer Co-Captain in Organizing Committee</role>
        <sort_key>19</sort_key>
        <first_name>Alex</first_name>
        <last_name>Sanchez-Stern</last_name>
        <affiliation>University of California, San Diego</affiliation>
        <bio>undefined</bio>
        <homepage_url>http://cseweb.ucsd.edu/~alexss/</homepage_url>
        <picture_url>https://popl18.sigplan.org/getProfileImage/alexsanchezstern/8f8df577-1227-40b6-86e8-2b553ee0c66d/small.jpg</picture_url>
      </person>
      <person>
        <role>Student Volunteer Co-Captain in Organizing Committee</role>
        <sort_key>20</sort_key>
        <first_name>Jakub</first_name>
        <last_name>Zalewski</last_name>
        <affiliation>University of Edinburgh</affiliation>
        <bio>undefined</bio>
        <picture_url>https://popl18.sigplan.org/getProfileImage/jakubzalewski/af33cf0f-4802-4ef9-8f97-639a923b6960/small.jpg</picture_url>
      </person>
    </persons>
  </event_details>
  <subevent>
    <subevent_id>ff32b6b2-cded-4d34-87d2-74834ed33181</subevent_id>
    <title>PLMW: Talks I</title>
    <subevent_type type="regular"/>
    <room>PLMW</room>
    <date>2018/01/09</date>
    <url>https://popl18.sigplan.org/track/PLMW-POPL-2018</url>
    <url_link_display>Programming Languages Mentoring Workshop</url_link_display>
    <tracks>
      <track>Programming Languages Mentoring Workshop</track>
    </tracks>
    <timeslot>
      <slot_id>08a592b1-ed91-4d54-8ac3-650f6533dd66</slot_id>
      <title>How to Become a Researcher</title>
      <room>Omni Hotel | PLMW</room>
      <date>2018/01/09</date>
      <start_time>09:30</start_time>
      <end_time>10:00</end_time>
      <description>undefined</description>
      <persons>
        <person>
          <role>Author</role>
          <sort_key>1</sort_key>
          <first_name>Armando</first_name>
          <last_name>Solar-Lezama</last_name>
          <affiliation>MIT CSAIL</affiliation>
          <bio>Armando Solar-Lezama is an associate professor at MIT where he leads the Computer Aided Programming Group. His research interests include software synthesis and its applications in diverse areas such as high-performance computing, information flow security and probabilistic programming.</bio>
          <picture_url>https://popl18.sigplan.org/getProfileImage/armandosolarlezama/7befe52d-6968-4786-9841-408800f80c71/small.jpg</picture_url>
        </person>
      </persons>
      <tracks>
        <track>Programming Languages Mentoring Workshop</track>
      </tracks>
    </timeslot>
    <timeslot>
      <slot_id>230ce4bf-3d22-42cd-8ef6-c9bd95c6f71d</slot_id>
      <title>LiquidHaskell Overview</title>
      <room>Omni Hotel | PLMW</room>
      <date>2018/01/09</date>
      <start_time>09:00</start_time>
      <end_time>09:30</end_time>
      <description>undefined</description>
      <persons>
        <person>
          <role>Author</role>
          <sort_key>1</sort_key>
          <first_name>Niki</first_name>
          <last_name>Vazou</last_name>
          <affiliation>University of Maryland</affiliation>
          <bio>undefined</bio>
          <homepage_url>https://nikivazou.github.io/</homepage_url>
          <picture_url>https://popl18.sigplan.org/getProfileImage/nikivazou/8cc6ddec-154b-47e9-b40d-c66e78476391/small.jpg</picture_url>
        </person>
      </persons>
      <tracks>
        <track>Programming Languages Mentoring Workshop</track>
      </tracks>
    </timeslot>
  </subevent>
  <subevent>
    <subevent_id>28b859ef-5bc8-47fa-9c1d-97e82fef644c</subevent_id>
    <title>NetPL 2018: Afternoon Session 1</title>
    <subevent_type type="regular"/>
    <room>NetPL</room>
    <date>2018/01/09</date>
    <url>https://popl18.sigplan.org/track/netpl-2018</url>
    <url_link_display>NetPL 2018</url_link_display>
    <tracks>
      <track>NetPL 2018</track>
    </tracks>
    <timeslot>
      <slot_id>60ae9917-e522-407a-b489-2e052c7526a1</slot_id>
      <title>Invited Talk 5</title>
      <room>Omni Hotel | NetPL</room>
      <date>2018/01/09</date>
      <start_time>15:00</start_time>
      <end_time>15:30</end_time>
      <description>undefined</description>
      <persons>
        <person>
          <role>invited speaker</role>
          <sort_key>1</sort_key>
          <first_name>Peyman</first_name>
          <last_name>Kazemian</last_name>
          <affiliation>Forward Networks</affiliation>
          <bio>undefined</bio>
        </person>
      </persons>
      <tracks>
        <track>NetPL 2018</track>
      </tracks>
    </timeslot>
    <timeslot>
      <slot_id>6ddeea1a-6653-4755-8e10-18e1868c1e27</slot_id>
      <title>Working Groups Debrief</title>
      <room>Omni Hotel | NetPL</room>
      <date>2018/01/09</date>
      <start_time>14:00</start_time>
      <end_time>14:30</end_time>
      <description>undefined</description>
      <tracks>
        <track>NetPL 2018</track>
      </tracks>
    </timeslot>
    <timeslot>
      <slot_id>c8b3c308-8724-48f8-b9fb-5f2d598a6fd6</slot_id>
      <title>Invited Talk 4</title>
      <room>Omni Hotel | NetPL</room>
      <date>2018/01/09</date>
      <start_time>14:30</start_time>
      <end_time>15:00</end_time>
      <description>undefined</description>
      <persons>
        <person>
          <role>invited speaker</role>
          <sort_key>1</sort_key>
          <first_name>Sharon</first_name>
          <last_name>Shoham</last_name>
          <affiliation>Tel Aviv university</affiliation>
          <bio>undefined</bio>
          <homepage_url>http://www.tau.ac.il/~sharonshoham/</homepage_url>
          <picture_url>https://popl18.sigplan.org/getProfileImage/sharonshoham/52ca243a-805e-43b9-9f5a-bd1bae25fccb/small.jpg</picture_url>
        </person>
      </persons>
      <tracks>
        <track>NetPL 2018</track>
      </tracks>
    </timeslot>
  </subevent>
  <subevent>
    <subevent_id>14078b2d-6d0c-4e45-b97d-332010872326</subevent_id>
    <title>PriSC 2018: Session 1</title>
    <subevent_type type="regular"/>
    <room>PriSC</room>
    <date>2018/01/13</date>
    <url>https://popl18.sigplan.org/track/prisc-2018</url>
    <url_link_display>Principles of Secure Compilation</url_link_display>
    <tracks>
      <track>Principles of Secure Compilation</track>
    </tracks>
    <timeslot>
      <slot_id>a7dc7cb4-401c-40ee-838c-d7665ae9537f</slot_id>
      <title>Linear capabilities for modular fully-abstract compilation of verified code</title>
      <room>Omni Hotel | PriSC</room>
      <date>2018/01/13</date>
      <start_time>10:30</start_time>
      <end_time>11:00</end_time>
      <description>We contribute a new approach for secure compilation of verified C code that we conjecture to be fully abstract. The approach relies on target language support for capabilities: a well-studied form of unforgeable memory pointers that enables fine-grained, efficient privilege separation. Such capabilities are implemented in special processors called capability machines, particularly the recent CHERI processor. More specifically, we rely on support for sealed capabilities (like CHERI’s), as well as a new form of capabilities that we call linear capabilities. Linear capabilities are specially treated by the hardware to ensure that they can never be copied. Using these target-language security primitives, our compiler relies on information from both the source program and its verification proof, i.e. it will be formally defined as a separation-logic-proof-directed compiler.</description>
      <persons>
        <person>
          <role>Author</role>
          <sort_key>1</sort_key>
          <first_name>Thomas</first_name>
          <last_name>Van Strydonck</last_name>
          <affiliation>KULeuven</affiliation>
          <bio>undefined</bio>
        </person>
        <person>
          <role>Author</role>
          <sort_key>2</sort_key>
          <first_name>Dominique</first_name>
          <last_name>Devriese</last_name>
          <affiliation>KU Leuven</affiliation>
          <bio>undefined</bio>
          <homepage_url>https://distrinet.cs.kuleuven.be/people/dominiqu</homepage_url>
          <picture_url>https://popl18.sigplan.org/getProfileImage/dominiquedevriese/08b1fc2d-d157-4905-9c9a-e1ff279ab345/small.jpg</picture_url>
        </person>
        <person>
          <role>Author</role>
          <sort_key>3</sort_key>
          <first_name>Frank</first_name>
          <last_name>Piessens</last_name>
          <affiliation>KU Leuven</affiliation>
          <bio>undefined</bio>
        </person>
      </persons>
      <tracks>
        <track>Principles of Secure Compilation</track>
      </tracks>
    </timeslot>
    <timeslot>
      <slot_id>d4f49615-70b1-464d-b07b-fcf076a3485f</slot_id>
      <title>Building Secure SGX Enclaves using F*, C/C++ and X64</title>
      <room>Omni Hotel | PriSC</room>
      <date>2018/01/13</date>
      <start_time>11:30</start_time>
      <end_time>12:00</end_time>
      <description>Intel SGX offers hardware mechanisms to isolate code and data running within enclaves from the rest of the platform. This enables security verification on a relatively small software TCB, but the task still involves complex low-level code.
Relying on the Everest verification toolchain, we use F* for developing specifications, code, and proofs; and then safely compile F* code to standalone C code. However, this does not account for all code running within the enclave, which also includes trusted C and assembly code for bootstrapping and for core libraries. Besides, we cannot expect all enclave applications to be rewritten in F*, so we also compile legacy C++ defensively, using variants of /guard that dynamically enforce their safety at runtime.
To reason about enclave security, we thus compose different sorts of code and verification styles, from fine-grained statically-verified F* to dynamically-monitored C++ and custom SGX instructions.
This involves two related program semantics: most of the verification is conducted within F* using the target semantics of Kremlin—a fragment of C with a structured memory—whereas SGX features and dynamic checks embedded by defensive C++ compilers require lower-level X64 code, for which we use the verified assembly language for Everest (VALE) and its embedding in F*.</description>
      <persons>
        <person>
          <role>Author</role>
          <sort_key>1</sort_key>
          <first_name>Anitha</first_name>
          <last_name>Gollamudi</last_name>
          <affiliation>undefined</affiliation>
          <bio>undefined</bio>
        </person>
        <person>
          <role>Author</role>
          <sort_key>2</sort_key>
          <first_name>Cédric</first_name>
          <last_name>Fournet</last_name>
          <affiliation>Microsoft Research</affiliation>
          <bio>undefined</bio>
          <homepage_url>http://research.microsoft.com/en-us/um/people/fournet/</homepage_url>
        </person>
      </persons>
      <tracks>
        <track>Principles of Secure Compilation</track>
      </tracks>
    </timeslot>
    <timeslot>
      <slot_id>e9f7080b-ece2-446a-a3af-af84f2241a17</slot_id>
      <title>Enforcing Well-bracketed Control Flow and Stack Encapsulation using Linear Capabilities</title>
      <room>Omni Hotel | PriSC</room>
      <date>2018/01/13</date>
      <start_time>11:00</start_time>