<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE event [<!ELEMENT zip_code (#PCDATA)><!ELEMENT url_link_display (#PCDATA)><!ELEMENT url (#PCDATA)><!ELEMENT tracks (track+)><!ELEMENT track (#PCDATA)><!ELEMENT title (#PCDATA)><!ELEMENT timeslot (slot_id?, title, room, date, start_time, end_time, description?, acm_doi?, persons?, tracks?, tags?)><!ELEMENT tags (tag+)><!ELEMENT tag (#PCDATA)><!ELEMENT suffix (#PCDATA)><!ELEMENT subevent_logo_url (#PCDATA)><!ELEMENT subevent_id (#PCDATA)>
<!ELEMENT subevent (subevent_id?, title, acronym?, timeslot*, subevent_type, description?, room, date, url?, url_link_display?, subevent_logo_url?, acm_doi?, persons?, tracks?, tags?, sponsor?, timeslot*)>
<!ELEMENT state (#PCDATA)><!ELEMENT start_time (#PCDATA)><!ELEMENT start_date (#PCDATA)><!ELEMENT sponsor (#PCDATA)><!ELEMENT sort_key (#PCDATA)><!ELEMENT slot_id (#PCDATA)><!ELEMENT subevent_type EMPTY><!ATTLIST subevent_type	type (case_study | demonstration | poster | regular | tutorial | workshop) #IMPLIED><!ELEMENT room (#PCDATA)><!ELEMENT role (#PCDATA)><!ELEMENT picture_url (#PCDATA)><!ELEMENT persons (person+)><!ELEMENT person (role, sort_key, first_name, middle_name?, last_name, suffix?, affiliation, acm_profile_id?, email?, bio?, homepage_url?, picture_url?)><!ELEMENT middle_name (#PCDATA)><!ELEMENT location (facility_name, facility_map_url?, address, city, state?, country, zip_code?)><!ELEMENT last_name (#PCDATA)><!ELEMENT homepage_url (#PCDATA)><!ELEMENT first_name (#PCDATA)><!ELEMENT facility_name (#PCDATA)><!ELEMENT facility_map_url (#PCDATA)><!ELEMENT event_type EMPTY><!ATTLIST event_type	type (conference|workshop|symposium) #IMPLIED><!ELEMENT event (event_details, subevent*, timeslot*)><!ELEMENT event_logo_url (#PCDATA)><!ELEMENT event_details (title, acronym, event_type, start_date, end_date, location, description, url?, url_link_display?, event_logo_url?, persons?)><!ELEMENT end_time (#PCDATA)><!ELEMENT end_date (#PCDATA)><!ELEMENT email (#PCDATA)><!ELEMENT description (#PCDATA)><!ELEMENT date (#PCDATA)><!ELEMENT country (#PCDATA)><!ELEMENT city (#PCDATA)><!ELEMENT bio (#PCDATA)><!ELEMENT affiliation (#PCDATA)><!ELEMENT address (#PCDATA)><!ELEMENT acronym (#PCDATA)><!ELEMENT acm_profile_id (#PCDATA)><!ELEMENT acm_doi (#PCDATA)>]>
<event>
  <event_details>
    <title>POPL 2019</title>
    <acronym>POPL 2019</acronym>
    <event_type type="conference"/>
    <start_date>2019/01/13</start_date>
    <end_date>2019/01/19</end_date>
    <location>
      <facility_name>Hotel Cascais Miragem</facility_name>
      <address>Av.Marginal n.8554</address>
      <city>Cascais/Lisbon</city>
      <country>Portugal</country>
    </location>
    <description>Registration is now open! 
 
 Booking a room at the conference hotel 
 Visa information 
 
Program of POPL 2019 and co-located events 
List of papers conditionally accepted for POPL 2019 
List of tutorials at TutorialFest 
Information for students 
 
 Student volunteers 
 Financial support 
 Programming Languages Mentoring Workshop (PLMW) 
 Student Research Competition 
</description>
    <url>https://popl19.sigplan.org/home</url>
    <url_link_display>POPL 2019</url_link_display>
    <persons>
      <person>
        <role>Committee Member in Steering Committee, General Chair in Organizing Committee</role>
        <sort_key>1</sort_key>
        <first_name>Fritz</first_name>
        <last_name>Henglein</last_name>
        <affiliation>Department of Computer Science, University of Copenhagen (DIKU)</affiliation>
        <bio>undefined</bio>
        <homepage_url>http://www.diku.dk/~henglein</homepage_url>
        <picture_url>https://popl19.sigplan.org/getProfileImage/fritzhenglein/4984918d-01be-497a-b867-fbf1a77100e8/small.jpg</picture_url>
      </person>
      <person>
        <role>Chair in Steering Committee</role>
        <sort_key>2</sort_key>
        <first_name>Michael</first_name>
        <last_name>Hicks</last_name>
        <affiliation>University of Maryland, College Park</affiliation>
        <bio>Michael Hicks is a Professor in the Computer Science department and UMIACS at the University of Maryland, where he co-directs the laboratory for Programming Languages research (PLUM); he is the former Director of the Maryland Cybersecurity Center (MC2). 
His research focuses on using programming languages and analyses to improve the security, reliability, and availability of software. He is perhaps best known for his work exploring dynamic software updating, which is a technique by which software can be updated without shutting it down. He has explored the design of new programming languages and analysis tools for helping programmers find bugs and software vulnerabilities, and for identifying suspicious or incorrect program executions. 
His recent work has combined ideas from PL and cryptography, e.g., to ensure privacy preserving computations. He also leads the development of a new security-oriented programming contest, “build-it, break-it, fix-it,” which has been offered to the public and to students in his Coursera class on software security. He is the co-editor of the Programming Languages Enthusiast blog and Tweets at @michael_w_hicks.</bio>
        <homepage_url>http://www.cs.umd.edu/~mwh/</homepage_url>
        <picture_url>https://popl19.sigplan.org/getProfileImage/michaelhicks/aa64e3c6-3516-4e13-affe-77bc32c40565/small.jpg</picture_url>
      </person>
      <person>
        <role>Committee Member in Steering Committee</role>
        <sort_key>3</sort_key>
        <first_name>Rastislav</first_name>
        <last_name>Bodik</last_name>
        <affiliation>University of Washington</affiliation>
        <bio>undefined</bio>
        <homepage_url>https://homes.cs.washington.edu/~bodik</homepage_url>
        <picture_url>https://popl19.sigplan.org/getProfileImage/rastislavbodik/ae16ae8e-9d00-41c4-9067-0c37da65dde7/small.jpg</picture_url>
      </person>
      <person>
        <role>Committee Member in Steering Committee</role>
        <sort_key>4</sort_key>
        <first_name>Giuseppe</first_name>
        <last_name>Castagna</last_name>
        <affiliation>CNRS, France / University of Paris Diderot, France</affiliation>
        <bio>undefined</bio>
        <homepage_url>http://www.irif.fr/~gc/</homepage_url>
        <picture_url>https://popl19.sigplan.org/getProfileImage/giuseppecastagna/ca2a9ac8-d149-4486-87ed-b55ceb154a17/small.jpg</picture_url>
      </person>
      <person>
        <role>Artifact Evaluation Co-Chair in Organizing Committee</role>
        <sort_key>5</sort_key>
        <first_name>Benjamin</first_name>
        <last_name>Delaware</last_name>
        <affiliation>Purdue University</affiliation>
        <bio>undefined</bio>
        <homepage_url>https://www.cs.purdue.edu/homes/bendy/</homepage_url>
        <picture_url>https://popl19.sigplan.org/getProfileImage/benjamindelaware/39bbf6b3-d145-435c-8956-8acf8cfcaffa/small.jpg</picture_url>
      </person>
      <person>
        <role>Workshops Co-Chair in Organizing Committee</role>
        <sort_key>6</sort_key>
        <first_name>Marco</first_name>
        <last_name>Gaboardi</last_name>
        <affiliation>University at Buffalo, SUNY</affiliation>
        <bio>Marco Gaboardi is an assistant professor in the Department of Computer Science and Engineering at the University at Buffalo, SUNY. Previously, he was a faculty at the University of Dundee, Scotland. He received his PhD from the University of Torino, Italy, and the Institute National Polytechnique de Lorraine, France. He was a visitor scholar at the University of Pennsylvania and at Harvard’s CRCS center. He has been the recipient of a EU Marie Curie Fellowship. His research is in programming languages, differential privacy, and logic.</bio>
        <homepage_url>http://www.buffalo.edu/~gaboardi</homepage_url>
        <picture_url>https://popl19.sigplan.org/getProfileImage/marcogaboardi/76ff8963-9672-4f16-87bc-3f0d75ce589b/small.jpg</picture_url>
      </person>
      <person>
        <role>Committee Member in Steering Committee</role>
        <sort_key>7</sort_key>
        <first_name>Jeremy</first_name>
        <last_name>Gibbons</last_name>
        <affiliation>Department of Computer Science, University of Oxford</affiliation>
        <bio>I am Professor of Computing in the Department of Computer Science at the University of Oxford. I am currently Director of the Software Engineering Programme, which offers part-time professional Masters’ degrees in Software Engineering and in Software and Systems Security. I also lead the Algebra of Programming research group. I am Editor-in-Chief of the Journal of Functional Programming, Past Vice Chair of ACM SIGPLAN, Past Chair of IFIP WG2.1. Before taking up this post in 1999, I held lectureships at Oxford Brookes University and the University of Auckland, New Zealand.</bio>
        <homepage_url>http://www.cs.ox.ac.uk/jeremy.gibbons/</homepage_url>
        <picture_url>https://popl19.sigplan.org/getProfileImage/jeremygibbons/17403e55-a926-41cf-ae21-08abecea187c/small.jpg</picture_url>
      </person>
      <person>
        <role>Committee Member in Steering Committee</role>
        <sort_key>8</sort_key>
        <first_name>Andrew D.</first_name>
        <last_name>Gordon</last_name>
        <affiliation>Microsoft Research and University of Edinburgh</affiliation>
        <bio>I am a Principal Researcher at Microsoft Research, Cambridge, where I manage Programming Principles and Tools. As a part-time position, I also hold the Chair in Computer Security and am a member of the Laboratory for Foundations of Computer Science and the Security and Privacy group in the School of Informatics in the University of Edinburgh. I convene the University of Edinburgh Microsoft Research Joint Initiative in Informatics. I participate in the Data Science PhD programme. My current research is on probabilistic programming for machine learning.</bio>
        <homepage_url>https://www.microsoft.com/en-us/research/people/adg/</homepage_url>
        <picture_url>https://popl19.sigplan.org/getProfileImage/andrewdgordon/6a7c06a4-cf70-4529-ad02-55b979e93f82/small.jpg</picture_url>
      </person>
      <person>
        <role>Publicity Chair in Organizing Committee</role>
        <sort_key>9</sort_key>
        <first_name>Michael</first_name>
        <last_name>Greenberg</last_name>
        <affiliation>Pomona College</affiliation>
        <bio>undefined</bio>
        <homepage_url>http://www.cs.pomona.edu/~michael/</homepage_url>
        <picture_url>https://popl19.sigplan.org/getProfileImage/michaelgreenberg/3c177ea6-ac3c-4ddb-9f4e-ac5d7b568e07/small.jpg</picture_url>
      </person>
      <person>
        <role>Artifact Evaluation Co-Chair in Organizing Committee</role>
        <sort_key>10</sort_key>
        <first_name>Cătălin</first_name>
        <last_name>Hriţcu</last_name>
        <affiliation>Inria Paris</affiliation>
        <bio>Catalin is a tenured Research Scientist at Inria Paris where he develops rigorous formal techniques for solving security problems. He is particularly interested in formal methods for security (memory safety, compartmentalization, dynamic monitoring, integrity, security protocols, information flow), programming languages (type systems, verification, proof assistants, property-based testing, semantics, formal metatheory, certified tools), and the design and verification of security-critical systems (reference monitors, secure compilers, microkernels, secure hardware). He is actively involved in the design of the F* verification system and was recently awarded an ERC Starting Grant on secure compilation. Catalin was a PhD student at Saarland University and a Research Associate at University of Pennsylvania before joining Inria Paris in 2013.</bio>
        <homepage_url>http://prosecco.gforge.inria.fr/personal/hritcu/</homepage_url>
        <picture_url>https://popl19.sigplan.org/getProfileImage/catalinhritcu/e262cec6-3e6b-47cc-ad61-b5c5b07953a1/small.jpg</picture_url>
      </person>
      <person>
        <role>Committee Member in Steering Committee</role>
        <sort_key>11</sort_key>
        <first_name>Ranjit</first_name>
        <last_name>Jhala</last_name>
        <affiliation>University of California, San Diego</affiliation>
        <bio>Nom nom. Chomp. Burp.</bio>
        <homepage_url>http://ranjitjhala.github.io</homepage_url>
        <picture_url>https://popl19.sigplan.org/getProfileImage/ranjitjhala/afbdab69-ed23-4022-b7a4-2c57128f20ec/small.jpg</picture_url>
      </person>
      <person>
        <role>Workshops Co-Chair in Organizing Committee</role>
        <sort_key>12</sort_key>
        <first_name>Zachary</first_name>
        <last_name>Kincaid</last_name>
        <affiliation>Princeton University</affiliation>
        <bio>undefined</bio>
        <homepage_url>http://www.cs.princeton.edu/~zkincaid</homepage_url>
        <picture_url>https://popl19.sigplan.org/getProfileImage/zacharykincaid/a26b486e-94a5-45f1-a8b3-9a2221495ff7/small.jpg</picture_url>
      </person>
      <person>
        <role>Website Chair in Organizing Committee</role>
        <sort_key>13</sort_key>
        <first_name>Hsiang-Shang ‘Josh’</first_name>
        <last_name>Ko</last_name>
        <affiliation>National Institute of Informatics, Japan</affiliation>
        <bio>undefined</bio>
        <homepage_url>https://josh-hs-ko.github.io</homepage_url>
        <picture_url>https://popl19.sigplan.org/getProfileImage/hsiangshangko/9c5db602-95a9-413b-a2d8-a4121be09c2c/small.jpg</picture_url>
      </person>
      <person>
        <role>Committee Member in Steering Committee</role>
        <sort_key>14</sort_key>
        <first_name>Rupak</first_name>
        <last_name>Majumdar</last_name>
        <affiliation>MPI-SWS, Germany</affiliation>
        <bio>undefined</bio>
        <homepage_url>http://www.mpi-sws.org/~rupak</homepage_url>
        <picture_url>https://popl19.sigplan.org/getProfileImage/rupakmajumdar/3289b197-9f9a-4880-94c5-d9cf6d764bb1/small.jpg</picture_url>
      </person>
      <person>
        <role>Registration in Organizing Committee</role>
        <sort_key>15</sort_key>
        <first_name>Carole</first_name>
        <last_name>Mann</last_name>
        <affiliation>R.S.L</affiliation>
        <bio>undefined</bio>
        <picture_url>https://popl19.sigplan.org/getProfileImage/carolemann/3ed7bc7a-bb13-4ef4-b9b8-9b5079757292/small.jpg</picture_url>
      </person>
      <person>
        <role>Committee Member in Steering Committee</role>
        <sort_key>16</sort_key>
        <first_name>Andrew</first_name>
        <last_name>Myers</last_name>
        <affiliation>Cornell University</affiliation>
        <bio>Andrew Myers is a Professor in the Department of Computer Science at Cornell University in Ithaca, NY. His research interests include programming languages, computer security, and distributed and persistent programming systems. Myers is an ACM Fellow. He has received awards for papers appearing in POPL’99, SOSP’01, SOSP’07, CIDR’13, PLDI’13, and PLDI’15. Myers is currently the Editor-in-Chief for ACM Transactions on Programming Languages and Systems (TOPLAS). He has also served as program chair or co-chair for a few conferences: ACM POPL 2018, ACM CCS 2016, POST 2014, IEEE CSF 2010, and IEEE S&amp;amp;P 2009.</bio>
        <homepage_url>http://www.cs.cornell.edu/andru</homepage_url>
        <picture_url>https://popl19.sigplan.org/getProfileImage/andrewmyers/88baadd2-5ed8-4687-b205-3cbbe8b1a848/small.jpg</picture_url>
      </person>
      <person>
        <role>Student Volunteer Co-Captain in Organizing Committee</role>
        <sort_key>17</sort_key>
        <first_name>Carlos</first_name>
        <last_name>Mão de Ferro</last_name>
        <affiliation>LASIGE, Faculty of Sciences, University of Lisbon</affiliation>
        <bio>undefined</bio>
        <homepage_url>http://www.lasige.di.fc.ul.pt/user/36</homepage_url>
        <picture_url>https://popl19.sigplan.org/getProfileImage/carlosmaodeferro/9e89ef60-4e85-415b-88de-1fb9f28ef170/small.jpg</picture_url>
      </person>
      <person>
        <role>Committee Member in Steering Committee</role>
        <sort_key>18</sort_key>
        <first_name>Brigitte</first_name>
        <last_name>Pientka</last_name>
        <affiliation>McGill University</affiliation>
        <bio>undefined</bio>
        <homepage_url>http://www.cs.mcgill.ca/~bpientka/</homepage_url>
        <picture_url>https://popl19.sigplan.org/getProfileImage/brigittepientka/de1fcba2-a8fd-4b6e-a4f2-b7d397fef2cf/small.jpg</picture_url>
      </person>
      <person>
        <role>Student Volunteer Co-Captain in Organizing Committee</role>
        <sort_key>19</sort_key>
        <first_name>Alex</first_name>
        <last_name>Sanchez-Stern</last_name>
        <affiliation>University of California, San Diego</affiliation>
        <bio>undefined</bio>
        <homepage_url>http://cseweb.ucsd.edu/~alexss/</homepage_url>
        <picture_url>https://popl19.sigplan.org/getProfileImage/alexsanchezstern/8f8df577-1227-40b6-86e8-2b553ee0c66d/small.jpg</picture_url>
      </person>
      <person>
        <role>Conference Coordinator in Organizing Committee, Treasurer in Organizing Committee</role>
        <sort_key>20</sort_key>
        <first_name>Annabel</first_name>
        <last_name>Satin</last_name>
        <affiliation>P.C.K.</affiliation>
        <bio>undefined</bio>
        <picture_url>https://popl19.sigplan.org/getProfileImage/annabelsatin/5e2fc743-bd68-4432-86af-99b4a6b6bf60/small.jpg</picture_url>
      </person>
      <person>
        <role>Committee Member in Steering Committee</role>
        <sort_key>21</sort_key>
        <first_name>Peter</first_name>
        <last_name>Thiemann</last_name>
        <affiliation>University of Freiburg, Germany</affiliation>
        <bio>undefined</bio>
        <picture_url>https://popl19.sigplan.org/getProfileImage/peterthiemann/43fc0175-1745-4b3a-b626-86e10da76b86/small.jpg</picture_url>
      </person>
      <person>
        <role>Local Arrangements Chair in Organizing Committee</role>
        <sort_key>22</sort_key>
        <first_name>Vasco</first_name>
        <last_name>Vasconcelos</last_name>
        <affiliation>LASIGE, Faculty of Sciences, University of Lisbon</affiliation>
        <bio>undefined</bio>
        <homepage_url>http://www.di.fc.ul.pt/~vv/</homepage_url>
        <picture_url>https://popl19.sigplan.org/getProfileImage/vascovasconcelos/b1bd0216-3fdb-4835-a89a-1e03a5fd6714/small.jpg</picture_url>
      </person>
      <person>
        <role>Student Research Competition Chair in Organizing Committee</role>
        <sort_key>23</sort_key>
        <first_name>Niki</first_name>
        <last_name>Vazou</last_name>
        <affiliation>IMDEA Software Institute</affiliation>
        <bio>undefined</bio>
        <homepage_url>https://nikivazou.github.io/</homepage_url>
        <picture_url>https://popl19.sigplan.org/getProfileImage/nikivazou/8cc6ddec-154b-47e9-b40d-c66e78476391/small.jpg</picture_url>
      </person>
      <person>
        <role>Committee Member in Steering Committee, Industrial Relations Chair in Organizing Committee</role>
        <sort_key>24</sort_key>
        <first_name>David</first_name>
        <last_name>Walker</last_name>
        <affiliation>Princeton University</affiliation>
        <bio>undefined</bio>
        <homepage_url>http://www.cs.princeton.edu/~dpw/</homepage_url>
        <picture_url>https://popl19.sigplan.org/getProfileImage/davidwalker/8763137a-03a5-4963-8639-e9f2a3cc8ac9/small.jpg</picture_url>
      </person>
      <person>
        <role>Committee Member in Steering Committee, Program Chair in Organizing Committee</role>
        <sort_key>25</sort_key>
        <first_name>Stephanie</first_name>
        <last_name>Weirich</last_name>
        <affiliation>University of Pennsylvania, USA</affiliation>
        <bio>undefined</bio>
        <homepage_url>https://www.cis.upenn.edu/~sweirich/</homepage_url>
        <picture_url>https://popl19.sigplan.org/getProfileImage/stephanieweirich/1f63ace9-e52a-4efc-b20b-ee75b5d7d091/small.jpg</picture_url>
      </person>
      <person>
        <role>Video Chair in Organizing Committee</role>
        <sort_key>26</sort_key>
        <first_name>Jakub</first_name>
        <last_name>Zalewski</last_name>
        <affiliation>undefined</affiliation>
        <bio>undefined</bio>
        <picture_url>https://popl19.sigplan.org/getProfileImage/jakubzalewski/33493c56-89a9-4187-9eff-4517d11c9818/small.jpg</picture_url>
      </person>
    </persons>
  </event_details>
  <subevent>
    <subevent_id>b446a052-3e47-410e-8386-1dfe779069f7</subevent_id>
    <title>POPL Student Research Competition: SRC Reception</title>
    <timeslot>
      <slot_id>1d8634ef-86b2-40fd-9004-94136b0dd3a0</slot_id>
      <title>Session: POPL Student Research Competition - SRC Reception</title>
      <room>Hotel Cascais Miragem | Galeria</room>
      <date>2019/01/16</date>
      <start_time>18:30</start_time>
      <end_time>19:30</end_time>
      <tracks>
        <track>Student Research Competition</track>
      </tracks>
    </timeslot>
    <subevent_type type="regular"/>
    <room>Hotel Cascais Miragem | Galeria</room>
    <date>2019/01/16</date>
    <url>https://popl19.sigplan.org/track/POPL-2019-Student-Research-Competition</url>
    <url_link_display>Student Research Competition</url_link_display>
    <tracks>
      <track>Student Research Competition</track>
    </tracks>
    <timeslot>
      <slot_id>0052ec68-15fe-48db-be4c-d718b4121cab</slot_id>
      <title>SRC Reception</title>
      <room>Hotel Cascais Miragem | Galeria</room>
      <date>2019/01/16</date>
      <start_time>18:30</start_time>
      <end_time>19:30</end_time>
      <description>undefined</description>
      <tracks>
        <track>Student Research Competition</track>
      </tracks>
    </timeslot>
  </subevent>
  <subevent>
    <subevent_id>548f7db3-08a1-4d4f-ab78-47790016e35c</subevent_id>
    <title>BEAT: Session 2</title>
    <timeslot>
      <slot_id>55e66baf-b4b1-45a1-a49d-bf79bf5835ee</slot_id>
      <title>Session: BEAT - Session 2</title>
      <room>Hotel Cascais Miragem | Sala VII</room>
      <date>2019/01/13</date>
      <start_time>11:00</start_time>
      <end_time>12:30</end_time>
      <persons>
        <person>
          <role>Session Chair</role>
          <sort_key>1</sort_key>
          <first_name>Dominic</first_name>
          <last_name>Orchard</last_name>
          <affiliation>University of Kent, UK</affiliation>
          <bio>Dr Dominic Orchard is a Lecturer in the School of Computing at the University of Kent, UK and he is a fellow of the SSI. His research interests are programming language design and semantics, mathematically structured programming, effect and coeffect systems, embedded domain-specific languages (esp. for parallelisation), and applying programming language research to computational science.</bio>
          <homepage_url>http://dorchard.co.uk</homepage_url>
          <picture_url>https://popl19.sigplan.org/getProfileImage/dominicorchard/f448aa26-a342-457c-91a6-3f9525a759a3/small.jpg</picture_url>
        </person>
      </persons>
      <tracks>
        <track>BEAT 2019: Fourth Workshop on Behavioral Types</track>
      </tracks>
    </timeslot>
    <subevent_type type="regular"/>
    <room>Hotel Cascais Miragem | Sala VII</room>
    <date>2019/01/13</date>
    <url>https://popl19.sigplan.org/track/beat-2019-papers</url>
    <url_link_display>BEAT 2019: Fourth Workshop on Behavioral Types</url_link_display>
    <tracks>
      <track>BEAT 2019: Fourth Workshop on Behavioral Types</track>
    </tracks>
    <timeslot>
      <slot_id>1d3224e1-9792-4990-85f8-61f76dca7cc7</slot_id>
      <title>Global Types with Internal Delegation</title>
      <room>Hotel Cascais Miragem | Sala VII</room>
      <date>2019/01/13</date>
      <start_time>11:50</start_time>
      <end_time>12:10</end_time>
      <description>In this talk we report on recent work in which we investigate a new form of delegation for multiparty session calculi. A paper describing this proposal has been submitted for publication to a journal. In the following after a very brief introduction we present our proposal through an example. Usually, delegation allows a session participant to appoint a participant in another session to act on her behalf. This means that delegation is inherently an inter-session mechanism, which requires session interleaving. Hence delegation falls outside the descriptive power of global types, which specify single sessions. As a consequence, properties such as deadlock-freedom or lock-freedom are difficult to ensure in the presence of delegation. We adopt a different view of delegation, by allowing participants to delegate tasks to each other within the same multiparty session. This way, delegation occurs within a single session (internal delegation) and may be captured by its global type. To increase flexibility in the use of delegation, our calculus uses connecting communications, which allow optional participants in the branches of choices. By these means, we are able to express conditional delegation. We present a session type system based on global types with internal delegation, and show that it ensures the usual safety properties of multiparty sessions, together with a progress property</description>
      <persons>
        <person>
          <role>Author</role>
          <sort_key>1</sort_key>
          <first_name>Ilaria</first_name>
          <last_name>Castellani</last_name>
          <affiliation>INRIA Sophia Antipolis, France</affiliation>
          <bio>undefined</bio>
          <homepage_url>http://www-sop.inria.fr/members/Ilaria.Castellani/</homepage_url>
          <picture_url>https://popl19.sigplan.org/getProfileImage/ilariacastellani/47b6f877-6713-449c-8974-610a9bfd2cf1/small.jpg</picture_url>
        </person>
        <person>
          <role>Author</role>
          <sort_key>2</sort_key>
          <first_name>Mariangiola</first_name>
          <last_name>Dezani</last_name>
          <affiliation>Università di Torino</affiliation>
          <bio>Master in Physics at the University of Torino cum laude (1970). Full professor of ‘‘Teoria e Applicazioni delle Macchine Calcolatrici’’ at the University of Torino since 31/10/81. Dean of the Computer Science Department of Torino University since 05. 